//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Real__estate.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Advertisement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Advertisement()
        {
            this.Images = new HashSet<Image>();
            this.Reports = new HashSet<Report>();
        }

        public int adsId { get; set; }
        [Required, StringLength(maximumLength: 100, MinimumLength = 20)]
        public string Tiltle { get; set; }
        [Column(TypeName = "date")]
        [Required, DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime ReleaseDate { get; set; }
        [Column(TypeName = "date")]
        [Required, DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime ExpirationDate { get; set; }
        public Nullable<int> SellerId { get; set; }
        public Nullable<int> AgentId { get; set; }
        public int PaymentId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Describe { get; set; }
        [StringLength(10)]
        public string CurrentSymbol { get; set; }
        public double priceOfAds { get; set; }
        [Required]
        public double EstatePrice { get; set; }
        public double Facade { get; set; }
        public double Gateway { get; set; }
        public int floors { get; set; }
        public int Bedrooms { get; set; }
        public int Toilets { get; set; }

        [StringLength(250)]
        public string furniture { get; set; }

        [Required]
        public double Area { get; set; }

        [Required, StringLength(50)]
        public string Cityprovince { get; set; }

        [Required, StringLength(50)]
        public string District { get; set; }

        [Required, StringLength(50)]
        public string Ward { get; set; }

        [Required, StringLength(50)]
        public string Street { get; set; }

        public bool isActivate { get; set; }
        public Nullable<int> UserId { get; set; }
        [Required]
        public int StatusHouse { get; set; }

        public virtual Agent Agent { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Images { get; set; }
        public virtual Payment Payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report> Reports { get; set; }
        public virtual Seller Seller { get; set; }
        public virtual User User { get; set; }
        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (ExpirationDate < ReleaseDate)
            {
                yield return new ValidationResult("Expiration Date must be greater than Release Date", new[] { "ExpirationDate" });
            }
        }
    }
}
