//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Real__estate.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Image
    {
        public int ImageId { get; set; }
        [Required]
        public string FileName { get; set; }
        [Required]
        public string Extension { get; set; }
        public Nullable<int> AdsId { get; set; }

        public virtual Advertisement Advertisement { get; set; }
    }
}
