//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Real__estate.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Report
    {
        public int ReportId { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public Nullable<int> AdsId { get; set; }
        public Nullable<int> SellerId { get; set; }
        public Nullable<int> AgentId { get; set; }
        public Nullable<double> Price { get; set; }

        public virtual Advertisement Advertisement { get; set; }
        public virtual Agent Agent { get; set; }
        public virtual Seller Seller { get; set; }
    }
}
